name = input()
price = int(input())
mass = int(input())
money = int(input())
print(f"Чек")
print(f"{name} - {mass}кг - {price}руб/кг")
print(f"Итого: {price * mass}руб")
print(f"Внесено: {money}руб")
print(f"Сдача: {int(money - price * mass)}руб")